repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-yaml
        args:
          - "--unsafe"
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    - id: check-added-large-files
      args:
        - "--maxkb=1024"
    - id: check-case-conflict
    - id: check-symlinks
